language: php

php:
  - 5.3
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - ./.travis.install.sh

script:
  - phpunit --coverage-clover ./build/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/clover.xml

matrix:
  allow_failures:
    - php: 5.3.3
    - php: hhvm
    - php: hhvm-nightly