<?php

namespace Fwk\Db;


class User extends \stdClass
{
    public $emails;
    
    public function __construct() {
        $this->emails = new Relations\Many2Many(
                'id', 
                'user_id', 
                'fwkdb_test_emails', 
                'fwkdb_test_users_emails', 
                'id', 
                'email_id', 
                'Email'
        );
    }
}

class Email extends \stdClass
{
}

/**
 * Test class for Accessor.
 * Generated by PHPUnit on 2012-05-27 at 17:46:42.
 */
class BasicEntityRelationsTest extends \PHPUnit_Framework_TestCase {

    /**
     *
     * @var \Fwk\Db\Connection
     */
    protected $connection;
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->connection = new Connection(array(
            'memory'    => true,
            'driver'    => 'pdo_sqlite'
        ));
        
        \FwkDbTestUtil::createTestDb($this->connection);
    }

    protected function tearDown()
    {
        \FwkDbTestUtil::dropTestDb($this->connection);
    }
    
    public function testMany2ManySave()
    {
        $u = new User;
        $u->username = "joebar";
        
        $e = new Email();
        $e->email = "joe@bar.com";
        $e->verified = 1;
        
        $this->assertEquals(0, count($this->connection->table('fwkdb_test_users')->finder()->all()));
        $this->assertEquals(0, count($this->connection->table('fwkdb_test_emails')->finder()->all()));
        
        $u->emails[] = $e;
        $this->connection->table('fwkdb_test_users')->save($u);
        
        $this->assertEquals(1, count($this->connection->table('fwkdb_test_users')->finder()->all()));
        $this->assertEquals(1, count($this->connection->table('fwkdb_test_emails')->finder()->all()));
    }
}