<?php

namespace Fwk\Db;

/**
 * Test class for Accessor.
 * Generated by PHPUnit on 2012-05-27 at 17:46:42.
 */
class BasicEntityMovesTest extends \PHPUnit_Framework_TestCase
{
    protected $connection;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->connection = new Connection(array(
            'memory'    => true,
            'driver'    => 'pdo_sqlite'
        ));

        \FwkDbTestUtil::createTestDb($this->connection);
    }

    protected function tearDown()
    {
        \FwkDbTestUtil::dropTestDb($this->connection);
    }

    public function testCreateAndInsert()
    {
        $this->assertEquals(0, count($this->connection->table("fwkdb_test_users")->finder()->all()));
        $obj = new \stdClass;
        $obj->username = "joeBar";

        $this->connection->table("fwkdb_test_users")->save($obj);
        $this->assertEquals(1, count($this->connection->table("fwkdb_test_users")->finder()->all()));
    }

    public function testCreateAndUpdate()
    {
        $this->assertEquals(0, count($this->connection->table("fwkdb_test_users")->finder()->all()));
        $obj = new \stdClass;
        $obj->username = "joeBar";
        $this->connection->table("fwkdb_test_users")->save($obj);

        $my = $this->connection->table('fwkdb_test_users')->finder()->find(array('username' => "joeBar"));
        $this->assertEquals(1, count($my));
        $obj = $my[0];
        $this->assertEquals("joeBar", $obj->username);
        $obj->username = "joeBarUPDATED";
        $this->connection->table("fwkdb_test_users")->save($obj);

        $my = $this->connection->table('fwkdb_test_users')->finder()->find(array('username' => "joeBar"));
        $this->assertEquals(0, count($my));
        $my = $this->connection->table('fwkdb_test_users')->finder()->find(array('username' => "joeBarUPDATED"));
        $this->assertEquals(1, count($my));
    }

    public function testCreateAndDelete()
    {
        $this->assertEquals(0, count($this->connection->table("fwkdb_test_users")->finder()->all()));
        $obj = new \stdClass;
        $obj->username = "joeBar";

        $this->connection->table("fwkdb_test_users")->save($obj);
        $this->assertEquals(1, count($this->connection->table("fwkdb_test_users")->finder()->all()));

        $this->connection->table("fwkdb_test_users")->delete($obj);
        $this->assertEquals(0, count($this->connection->table("fwkdb_test_users")->finder()->all()));
    }
}
