<?php
namespace Fwk\Db;

use Fwk\Db\Events\FreshEvent;

class TestListener
{
    public function onFresh(FreshEvent $event)
    {
        $event->getEntity()->property = "listener!";
    }
}

class User2 extends \stdClass implements EventSubscriber
{
    public $emails;

    public $metas;

    public $phone;

    public $property = null;

    public function __construct()
    {
        $this->emails = new Relations\Many2Many(
            'id',
            'user_id',
            'fwkdb_test_emails',
            'fwkdb_test_users_emails',
            'id',
            'email_id',
            'Fwk\Db\Email2'
        );

        $this->metas = new Relations\One2Many(
            'id',
            'user_id',
            'fwkdb_test_users_metas'
        );
        $this->metas->setReference('name');

        $this->phone = new Relations\One2One('phone_id', 'id', 'fwkdb_test_phones');
    }

    /**
     * @return array
     */
    public function getListeners()
    {
        return array(
            new TestListener()
        );
    }
}

class Email2 extends \stdClass
{
}

/**
 * Test class for Accessor.
 * Generated by PHPUnit on 2012-05-27 at 17:46:42.
 */
class EventSubscriberTest extends \PHPUnit_Framework_TestCase
{
    /**
     *
     * @var \Fwk\Db\Connection
     */
    protected $connection;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->connection = new Connection(array(
            'memory'    => true,
            'driver'    => 'pdo_sqlite'
        ));

        \FwkDbTestUtil::createTestDb($this->connection);

        $obj = new \stdClass;
        $obj->username = "joeBar";
        $this->connection->table("fwkdb_test_users")->save($obj);
    }

    protected function tearDown()
    {
        \FwkDbTestUtil::dropTestDb($this->connection);
    }

    public function testListenerIsTriggered()
    {
        $obj = $this->connection->table("fwkdb_test_users")->finder()->setEntity('Fwk\Db\User2')->all();
        $this->assertEquals(1, count($obj));
        $this->assertEquals("listener!", $obj[0]->property);
    }
}
