<?php

namespace Fwk\Db;

/**
 * Test class for Finder.
 * Generated by PHPUnit on 2012-07-05 at 13:54:28.
 */
class FinderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Finder
     */
    protected $object;

    /**
     * @var Connection
     */
    protected $db;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->db = new Connection(array(
            'memory' => true,
            'driver' => 'pdo_sqlite'
        ));

        \FwkDbTestUtil::createTestDb($this->db);
        $this->object = new Finder(new Table('fwkdb_test_users'));
    }

    protected function tearDown()
    {
        \FwkDbTestUtil::dropTestDb($this->db);
    }

    /**
     */
    public function testGetConnectionFail()
    {
        $this->setExpectedException('\Fwk\Db\Exception');
        $this->object->getConnection();
    }

    public function testGetConnection()
    {
        $db = new Connection(array(
                    'memory' => true,
                    'driver' => 'pdo_sqlite'
                ));

        $this->object->setConnection($db);
        $this->assertEquals($db, $this->object->getConnection());
    }

    public function testPreventDoubleExecute()
    {
        $this->object->setConnection($this->db);

        $this->object->find(array('id' => 2));
        $this->setExpectedException('\Fwk\Db\Exception');
        $this->object->find(array('id' => 2));
    }

    public function testPreventOneDoubleExecute()
    {
        $this->object = $this->db->table('fwkdb_test_users')->finder();

        $this->object->one(2);
        $this->setExpectedException('\Fwk\Db\Exception');
        $this->object->one(2);
    }

    public function testMissingIdentifiers()
    {
        $this->object = $this->db->table('fwkdb_test_users_emails')->finder();
        $this->setExpectedException('\Fwk\Db\Exception');
        $this->object->one(2);
    }
}
