<?php

namespace Fwk\Db;

/**
 * Test class for Finder.
 * Generated by PHPUnit on 2012-07-05 at 13:54:28.
 */
class FinderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Finder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Finder(new Table('test_table'));
    }


    /**
     */
    public function testGetConnectionFail() {
        $this->setExpectedException('\Fwk\Db\Exception');
        $this->object->getConnection();
    }
    
    public function testGetConnection() {
        $db = new Connection(array(
                    'memory' => true,
                    'driver' => 'pdo_sqlite'
                ));
        
        $this->object->setConnection($db);
        $this->assertEquals($db, $this->object->getConnection());
    }
}
