<?php
namespace Fwk\Db;

use Fwk\Db\Listeners\Timestampable;

class User3 extends \stdClass implements EventSubscriberInterface
{
    public $created_at;

    public $updated_at;

    /**
     * @return array
     */
    public function getListeners()
    {
        return array(
            new Timestampable()
        );
    }
}

/**
 * Test class for Accessor.
 * Generated by PHPUnit on 2012-05-27 at 17:46:42.
 */
class TimestampableTest extends \PHPUnit_Framework_TestCase
{
    /**
     *
     * @var \Fwk\Db\Connection
     */
    protected $connection;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->connection = new Connection(array(
            'memory'    => true,
            'driver'    => 'pdo_sqlite'
        ));

        \FwkDbTestUtil::createTestDb($this->connection);
    }

    protected function tearDown()
    {
        \FwkDbTestUtil::dropTestDb($this->connection);
    }

    public function testTimestampable()
    {
        $obj = new User3();
        $obj->username = "joeBar";
        $this->assertNull($obj->created_at);

        $this->connection->table("fwkdb_test_users")->save($obj);

        $this->assertNotNull($obj->created_at);
        $creation = $obj->created_at;

        $this->assertNull($obj->updated_at);
        $obj->username = "joeBarUpdated";
        $this->connection->table("fwkdb_test_users")->save($obj);

        $this->assertEquals($creation, $obj->created_at);
        $this->assertNotNull($obj->updated_at);
    }
}
